sudo: required
services: docker

env:
  global:
  - DOCKER_REPO=buildpack-deps
  - secure: "NPhsaHjSLbnI/YdKLxE6jIwoSflk8l8ppELVLC0lnPKOtv1ssr4w2IjNQhXscIzZMGNRecqH+6KDDZz+CRnqSKk3nRFIeaE2HiosRCjNt5pgA+s8FXMmV4O3L3E7O8TmwC7pu3A5B00nqGtHaLo3F3pCyXyZiZJkJVJpBkucX0k="
  matrix:
  - VERSION=artful/amd64
  - VERSION=artful/arm64
  - VERSION=artful/armhf
  - VERSION=artful/i386
  - VERSION=artful/ppc64el
  - VERSION=artful/s390x
  - VERSION=bionic/amd64
  - VERSION=bionic/arm64
  - VERSION=bionic/armhf
  - VERSION=bionic/i386
  - VERSION=bionic/ppc64el
  - VERSION=bionic/s390x
  - VERSION=buster/amd64
  - VERSION=buster/arm64
  - VERSION=buster/armel
  - VERSION=buster/armhf
  - VERSION=buster/i386
  - VERSION=buster/mips
  - VERSION=buster/mips64el
  - VERSION=buster/mipsel
  - VERSION=buster/ppc64el
  - VERSION=buster/s390x
  - VERSION=jessie/amd64
  - VERSION=jessie/arm64
  - VERSION=jessie/armel
  - VERSION=jessie/armhf
  - VERSION=jessie/i386
  - VERSION=jessie/kfreebsd-amd64
  - VERSION=jessie/kfreebsd-i386
  - VERSION=jessie/mips
  - VERSION=jessie/mipsel
  - VERSION=jessie/powerpc
  - VERSION=jessie/ppc64el
  - VERSION=jessie/s390x
  - VERSION=sid/amd64
  - VERSION=sid/arm64
  - VERSION=sid/armel
  - VERSION=sid/armhf
  - VERSION=sid/hurd-i386
  - VERSION=sid/i386
  - VERSION=sid/kfreebsd-amd64
  - VERSION=sid/kfreebsd-i386
  - VERSION=sid/mips
  - VERSION=sid/mips64el
  - VERSION=sid/mipsel
  - VERSION=sid/ppc64el
  - VERSION=sid/s390x
  - VERSION=stretch/amd64
  - VERSION=stretch/arm64
  - VERSION=stretch/armel
  - VERSION=stretch/armhf
  - VERSION=stretch/i386
  - VERSION=stretch/mips
  - VERSION=stretch/mips64el
  - VERSION=stretch/mipsel
  - VERSION=stretch/ppc64el
  - VERSION=stretch/s390x
  - VERSION=trusty/amd64
  - VERSION=trusty/arm64
  - VERSION=trusty/armhf
  - VERSION=trusty/i386
  - VERSION=trusty/ppc64el
  - VERSION=wheezy/amd64
  - VERSION=wheezy/armel
  - VERSION=wheezy/armhf
  - VERSION=wheezy/i386
  - VERSION=wheezy/ia64
  - VERSION=wheezy/kfreebsd-amd64
  - VERSION=wheezy/kfreebsd-i386
  - VERSION=wheezy/mips
  - VERSION=wheezy/mipsel
  - VERSION=wheezy/powerpc
  - VERSION=wheezy/s390
  - VERSION=wheezy/s390x
  - VERSION=wheezy/sparc
  - VERSION=xenial/amd64
  - VERSION=xenial/arm64
  - VERSION=xenial/armhf
  - VERSION=xenial/i386
  - VERSION=xenial/ppc64el
  - VERSION=xenial/s390x

matrix:
  fast_finish: true
  exclude:
  - env: VERSION=jessie/kfreebsd-amd64
  - env: VERSION=jessie/kfreebsd-i386
  - env: VERSION=sid/hurd-i386
  - env: VERSION=sid/kfreebsd-amd64
  - env: VERSION=sid/kfreebsd-i386
  - env: VERSION=wheezy/ia64
  - env: VERSION=wheezy/kfreebsd-amd64
  - env: VERSION=wheezy/kfreebsd-i386
  allow_failures:
  - env: VERSION=artful/s390x
  - env: VERSION=wheezy/s390
  - env: VERSION=wheezy/sparc
  - env: VERSION=xenial/s390x

branches:
  only:
  - master

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - docker run --rm --privileged vicamo/binfmt-qemu:latest
  - cat /proc/sys/fs/binfmt_misc/qemu-*
  - env | sort
  - export image="${DOCKER_USER}/${DOCKER_REPO}:${VERSION%/*}-${VERSION#*/}"

script:
  - travis_wait make NO_SKIP=1 DOCKER_USER=${DOCKER_USER} DOCKER_REPO=${DOCKER_REPO} "${VERSION%/*}-${VERSION#*/}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a -n "$(docker images | grep ${DOCKER_USER}/${DOCKER_REPO})" ]; then
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
    for p in $(docker images | grep ${DOCKER_USER}/${DOCKER_REPO} | awk '{print $1":"$2}'); do
      docker push $p;
    done
  fi

notifications:
  slack:
    secure: JwJkvYYD4Q3iQi0pq6GNh2Blf9LLUVfOkfWIeMmomXYJgXyKsLvspnZdC+d8iQqQMAgDUkWS+K1EXVy92mcL+9YcGStlekuVF7hJCZlSJno3hLvtSrruA65JBwBojMKOZNZ7vtNCcFN/lVeFqUabrDezCzCSRYV+uTyVrXuqEnE=

# vim:set et ts=2 sw=2:
