language: bash
dist: trusty
sudo: required
services: docker

env:
  global:
  - DOCKER_REPO=buildpack-deps
  - secure: "NPhsaHjSLbnI/YdKLxE6jIwoSflk8l8ppELVLC0lnPKOtv1ssr4w2IjNQhXscIzZMGNRecqH+6KDDZz+CRnqSKk3nRFIeaE2HiosRCjNt5pgA+s8FXMmV4O3L3E7O8TmwC7pu3A5B00nqGtHaLo3F3pCyXyZiZJkJVJpBkucX0k="
  matrix:
  - VERSION=jessie/amd64
  - VERSION=jessie/arm64
  - VERSION=jessie/armel
  - VERSION=jessie/armhf
  - VERSION=jessie/i386
  - VERSION=jessie/kfreebsd-amd64
  - VERSION=jessie/kfreebsd-i386
  - VERSION=jessie/mips
  - VERSION=jessie/mipsel
  - VERSION=jessie/powerpc
  - VERSION=jessie/ppc64el
  - VERSION=jessie/s390x
  - VERSION=precise/amd64
  - VERSION=precise/armhf
  - VERSION=precise/i386
  - VERSION=sid/amd64
  - VERSION=sid/arm64
  - VERSION=sid/armel
  - VERSION=sid/armhf
  - VERSION=sid/hurd-i386
  - VERSION=sid/i386
  - VERSION=sid/kfreebsd-amd64
  - VERSION=sid/kfreebsd-i386
  - VERSION=sid/mips
  - VERSION=sid/mips64el
  - VERSION=sid/mipsel
  - VERSION=sid/ppc64el
  - VERSION=sid/s390x
  - VERSION=stretch/amd64
  - VERSION=stretch/arm64
  - VERSION=stretch/armel
  - VERSION=stretch/armhf
  - VERSION=stretch/i386
  - VERSION=stretch/mips
  - VERSION=stretch/mips64el
  - VERSION=stretch/mipsel
  - VERSION=stretch/ppc64el
  - VERSION=stretch/s390x
  - VERSION=trusty/amd64
  - VERSION=trusty/arm64
  - VERSION=trusty/armhf
  - VERSION=trusty/i386
  - VERSION=trusty/ppc64el
  - VERSION=wheezy/amd64
  - VERSION=wheezy/armel
  - VERSION=wheezy/armhf
  - VERSION=wheezy/i386
  - VERSION=wheezy/ia64
  - VERSION=wheezy/kfreebsd-amd64
  - VERSION=wheezy/kfreebsd-i386
  - VERSION=wheezy/mips
  - VERSION=wheezy/mipsel
  - VERSION=wheezy/powerpc
  - VERSION=wheezy/s390
  - VERSION=wheezy/s390x
  - VERSION=wheezy/sparc
  - VERSION=xenial/amd64
  - VERSION=xenial/arm64
  - VERSION=xenial/armhf
  - VERSION=xenial/i386
  - VERSION=xenial/ppc64el
  - VERSION=xenial/s390x
  - VERSION=yakkety/amd64
  - VERSION=yakkety/arm64
  - VERSION=yakkety/armhf
  - VERSION=yakkety/i386
  - VERSION=yakkety/ppc64el
  - VERSION=yakkety/s390x
  - VERSION=zesty/amd64
  - VERSION=zesty/arm64
  - VERSION=zesty/armhf
  - VERSION=zesty/i386
  - VERSION=zesty/ppc64el
  - VERSION=zesty/s390x

matrix:
  fast_finish: true
  exclude:
  - env: VERSION=jessie/kfreebsd-amd64
  - env: VERSION=jessie/kfreebsd-i386
  - env: VERSION=sid/hurd-i386
  - env: VERSION=sid/kfreebsd-amd64
  - env: VERSION=sid/kfreebsd-i386
  - env: VERSION=wheezy/ia64
  - env: VERSION=wheezy/kfreebsd-amd64
  - env: VERSION=wheezy/kfreebsd-i386
  allow_failures:
  - env: VERSION=wheezy/s390
  - env: VERSION=wheezy/sparc
  - env: VERSION=xenial/s390x
  - env: VERSION=yakkety/s390x
  - env: VERSION=zesty/s390x

branches:
  only:
  - master

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ devel universe'
    packages:
    - binfmt-support
    - qemu-user-static

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - export image="${DOCKER_USER}/${DOCKER_REPO}:${VERSION%/*}-${VERSION#*/}"

script:
  - make NO_SKIP=1 DOCKER_USER=${DOCKER_USER} DOCKER_REPO=${DOCKER_REPO} "${VERSION%/*}-${VERSION#*/}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a -n "$(docker images | grep ${DOCKER_USER}/${DOCKER_REPO})" ]; then
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
    for p in $(docker images | grep ${DOCKER_USER}/${DOCKER_REPO} | awk '{print $1":"$2}'); do
      docker push $p;
    done
  fi

# vim:set et ts=2 sw=2:
