dist: bionic
sudo: required
services: docker

env:
  global:
  - DOCKER_REPO=buildpack-deps
  - secure: "SjQXOjC+vsiBmUz7GH/yBabXELEuwsHr+5V17JXHXIdte3ZVnPFoIdLGwfAq3TAPAvlTkwSqswlo6Z/4N5Akr4ouXv8nLvHbWlhtrf/gvyZqpj41JGZuik3wy+uEbaUrZX0/hzFvsT4aZ1r7wdTHnL9PubhX+uBalDcQ48IjUqg="
  matrix:
  - VERSION=bionic/amd64
  - VERSION=bionic/arm64
  - VERSION=bionic/armhf
  - VERSION=bionic/i386
  - VERSION=bionic/ppc64el
  - VERSION=bionic/s390x
  - VERSION=bullseye/amd64
  - VERSION=bullseye/arm64
  - VERSION=bullseye/armel
  - VERSION=bullseye/armhf
  - VERSION=bullseye/i386
  - VERSION=bullseye/mips64el
  - VERSION=bullseye/mipsel
  - VERSION=bullseye/ppc64el
  - VERSION=bullseye/s390x
  - VERSION=buster/amd64
  - VERSION=buster/arm64
  - VERSION=buster/armel
  - VERSION=buster/armhf
  - VERSION=buster/i386
  - VERSION=buster/mips
  - VERSION=buster/mips64el
  - VERSION=buster/mipsel
  - VERSION=buster/ppc64el
  - VERSION=buster/s390x
  - VERSION=disco/amd64 QEMU_SUITE=bionic
  - VERSION=disco/arm64 QEMU_SUITE=bionic
  - VERSION=disco/armhf QEMU_SUITE=bionic
  - VERSION=disco/i386 QEMU_SUITE=bionic
  - VERSION=disco/ppc64el QEMU_SUITE=bionic
  - VERSION=disco/s390x QEMU_SUITE=bionic
  - VERSION=eoan/amd64
  - VERSION=eoan/arm64
  - VERSION=eoan/armhf
  - VERSION=eoan/i386
  - VERSION=eoan/ppc64el
  - VERSION=eoan/s390x
  - VERSION=focal/amd64
  - VERSION=focal/arm64
  - VERSION=focal/armhf
  - VERSION=focal/i386
  - VERSION=focal/ppc64el
  - VERSION=focal/s390x
  - VERSION=jessie/amd64
  - VERSION=jessie/armel
  - VERSION=jessie/armhf
  - VERSION=jessie/i386
  - VERSION=sid/alpha
  - VERSION=sid/amd64
  - VERSION=sid/arm64
  - VERSION=sid/armel
  - VERSION=sid/armhf
  - VERSION=sid/hppa
  - VERSION=sid/hurd-i386
  - VERSION=sid/i386
  - VERSION=sid/kfreebsd-amd64
  - VERSION=sid/kfreebsd-i386
  - VERSION=sid/m68k
  - VERSION=sid/mips64el
  - VERSION=sid/mipsel
  - VERSION=sid/powerpc
  - VERSION=sid/powerpcspe
  - VERSION=sid/ppc64
  - VERSION=sid/ppc64el
  - VERSION=sid/s390x
  - VERSION=sid/sh4
  - VERSION=sid/sparc64
  - VERSION=sid/x32
  - VERSION=stretch/amd64
  - VERSION=stretch/arm64
  - VERSION=stretch/armel
  - VERSION=stretch/armhf
  - VERSION=stretch/i386
  - VERSION=stretch/mips
  - VERSION=stretch/mips64el
  - VERSION=stretch/mipsel
  - VERSION=stretch/ppc64el
  - VERSION=stretch/s390x
  - VERSION=xenial/amd64 QEMU_SUITE=bionic
  - VERSION=xenial/arm64 QEMU_SUITE=bionic
  - VERSION=xenial/armhf QEMU_SUITE=bionic
  - VERSION=xenial/i386 QEMU_SUITE=bionic
  - VERSION=xenial/ppc64el QEMU_SUITE=bionic
  - VERSION=xenial/s390x QEMU_SUITE=bionic

matrix:
  fast_finish: true
  exclude:
  - env: VERSION=sid/hurd-i386
  - env: VERSION=sid/kfreebsd-amd64
  - env: VERSION=sid/kfreebsd-i386
  allow_failures:
  - env: VERSION=sid/alpha
  - env: VERSION=sid/hppa
  - env: VERSION=sid/m68k
  - env: VERSION=sid/powerpc
  - env: VERSION=sid/powerpcspe
  - env: VERSION=sid/ppc64
  - env: VERSION=sid/sh4
  - env: VERSION=sid/sparc64
  - env: VERSION=sid/x32
  - env: VERSION=xenial/s390x QEMU_SUITE=bionic
  # https://github.com/vicamo/docker_buildpack-deps/issues/46
  - env: VERSION=focal/s390x

branches:
  only:
  - master

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - export SUITE=${VERSION%/*}
  - export ARCH=${VERSION#*/}
  - docker run --rm --privileged vicamo/binfmt-qemu:${QEMU_SUITE:-${SUITE}}
  - cat /proc/sys/fs/binfmt_misc/qemu-*
  - env | sort
  - export image="${DOCKER_USER}/${DOCKER_REPO}:${SUITE}-${ARCH}"

script:
  - travis_wait make NO_SKIP=1 DOCKER_USER=${DOCKER_USER} DOCKER_REPO=${DOCKER_REPO} "${SUITE}-${ARCH}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a -n "$(docker images | grep ${DOCKER_USER}/${DOCKER_REPO})" ]; then
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
    for p in $(docker images | grep ${DOCKER_USER}/${DOCKER_REPO} | awk '{print $1":"$2}'); do
      docker push $p;
    done
  fi

notifications:
  slack:
    secure: JwJkvYYD4Q3iQi0pq6GNh2Blf9LLUVfOkfWIeMmomXYJgXyKsLvspnZdC+d8iQqQMAgDUkWS+K1EXVy92mcL+9YcGStlekuVF7hJCZlSJno3hLvtSrruA65JBwBojMKOZNZ7vtNCcFN/lVeFqUabrDezCzCSRYV+uTyVrXuqEnE=

# vim:set et ts=2 sw=2:
