dist: bionic
sudo: required
services: docker

env:
  global:
  - DOCKER_REPO=buildpack-deps
  - secure: "SjQXOjC+vsiBmUz7GH/yBabXELEuwsHr+5V17JXHXIdte3ZVnPFoIdLGwfAq3TAPAvlTkwSqswlo6Z/4N5Akr4ouXv8nLvHbWlhtrf/gvyZqpj41JGZuik3wy+uEbaUrZX0/hzFvsT4aZ1r7wdTHnL9PubhX+uBalDcQ48IjUqg="
  matrix:
  - VERSION=debian/bullseye/amd64
  - VERSION=debian/bullseye/arm64
  - VERSION=debian/bullseye/armel
  - VERSION=debian/bullseye/armhf
  - VERSION=debian/bullseye/i386
  - VERSION=debian/bullseye/mips64el
  - VERSION=debian/bullseye/mipsel
  - VERSION=debian/bullseye/ppc64el
  - VERSION=debian/bullseye/s390x
  - VERSION=debian/buster/amd64
  - VERSION=debian/buster/arm64
  - VERSION=debian/buster/armel
  - VERSION=debian/buster/armhf
  - VERSION=debian/buster/i386
  - VERSION=debian/buster/mips
  - VERSION=debian/buster/mips64el
  - VERSION=debian/buster/mipsel
  - VERSION=debian/buster/ppc64el
  - VERSION=debian/buster/s390x
  - VERSION=debian/sid/alpha
  - VERSION=debian/sid/amd64
  - VERSION=debian/sid/arm64
  - VERSION=debian/sid/armel
  - VERSION=debian/sid/armhf
  - VERSION=debian/sid/hppa
  - VERSION=debian/sid/hurd-i386
  - VERSION=debian/sid/i386
  - VERSION=debian/sid/kfreebsd-amd64
  - VERSION=debian/sid/kfreebsd-i386
  - VERSION=debian/sid/m68k
  - VERSION=debian/sid/mips64el
  - VERSION=debian/sid/mipsel
  - VERSION=debian/sid/powerpc
  - VERSION=debian/sid/powerpcspe
  - VERSION=debian/sid/ppc64
  - VERSION=debian/sid/ppc64el
  - VERSION=debian/sid/s390x
  - VERSION=debian/sid/sh4
  - VERSION=debian/sid/sparc64
  - VERSION=debian/sid/x32
  - VERSION=debian/stretch/amd64
  - VERSION=debian/stretch/arm64
  - VERSION=debian/stretch/armel
  - VERSION=debian/stretch/armhf
  - VERSION=debian/stretch/i386
  - VERSION=debian/stretch/mips
  - VERSION=debian/stretch/mips64el
  - VERSION=debian/stretch/mipsel
  - VERSION=debian/stretch/ppc64el
  - VERSION=debian/stretch/s390x
  - VERSION=ubuntu/bionic/amd64
  - VERSION=ubuntu/bionic/arm64
  - VERSION=ubuntu/bionic/armhf
  - VERSION=ubuntu/bionic/i386
  - VERSION=ubuntu/bionic/ppc64el
  - VERSION=ubuntu/bionic/s390x
  - VERSION=ubuntu/focal/amd64
  - VERSION=ubuntu/focal/arm64
  - VERSION=ubuntu/focal/armhf
  - VERSION=ubuntu/focal/ppc64el
  - VERSION=ubuntu/focal/s390x
  - VERSION=ubuntu/groovy/amd64
  - VERSION=ubuntu/groovy/arm64
  - VERSION=ubuntu/groovy/armhf
  - VERSION=ubuntu/groovy/ppc64el
  - VERSION=ubuntu/groovy/s390x
  - VERSION=ubuntu/hirsute/amd64
  - VERSION=ubuntu/hirsute/arm64
  - VERSION=ubuntu/hirsute/armhf
  - VERSION=ubuntu/hirsute/ppc64el
  - VERSION=ubuntu/hirsute/s390x
  - VERSION=ubuntu/xenial/amd64 QEMU_SUITE=bionic
  - VERSION=ubuntu/xenial/arm64 QEMU_SUITE=bionic
  - VERSION=ubuntu/xenial/armhf QEMU_SUITE=bionic
  - VERSION=ubuntu/xenial/i386 QEMU_SUITE=bionic
  - VERSION=ubuntu/xenial/ppc64el QEMU_SUITE=bionic
  - VERSION=ubuntu/xenial/s390x QEMU_SUITE=bionic

matrix:
  fast_finish: true
  exclude:
  - env: VERSION=debian/sid/hurd-i386
  - env: VERSION=debian/sid/kfreebsd-amd64
  - env: VERSION=debian/sid/kfreebsd-i386
  allow_failures:
  # https://github.com/vicamo/docker_buildpack-deps/issues/36
  - env: VERSION=debian/sid/alpha
  # https://github.com/vicamo/docker_buildpack-deps/issues/37
  - env: VERSION=debian/sid/powerpcspe
  # https://github.com/vicamo/docker_buildpack-deps/issues/48
  - env: VERSION=debian/sid/sparc64
  # https://github.com/vicamo/docker_buildpack-deps/issues/51
  - env: VERSION=debian/sid/x32
  # https://github.com/vicamo/docker_buildpack-deps/issues/7
  - env: VERSION=ubuntu/xenial/s390x QEMU_SUITE=bionic
  # https://github.com/vicamo/docker_buildpack-deps/issues/54
  - env: VERSION=debian/sid/i386
  - env: VERSION=debian/bullseye/i386
  # https://github.com/vicamo/docker_buildpack-deps/issues/55
  - env: VERSION=debian/sid/ppc64

branches:
  only:
  - master

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - export DISTRO=${VERSION%/*}
  - export SUITE=${DISTRO#*/}
  - export DISTRO=${DISTRO%/*}
  - export ARCH=${VERSION##*/}
  - docker run --rm --privileged vicamo/binfmt-qemu:${QEMU_SUITE:-${SUITE}}
  - cat /proc/sys/fs/binfmt_misc/qemu-*
  - env | sort
  - export image="${DOCKER_USER}/${DOCKER_REPO}:${SUITE}-${ARCH}"

script:
  - travis_wait make NO_SKIP=1 DOCKER_USER=${DOCKER_USER} DOCKER_REPO=${DOCKER_REPO} "${SUITE}-${ARCH}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a -n "$(docker images | grep ${DOCKER_USER}/${DOCKER_REPO})" ]; then
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
    for p in $(docker images | grep ${DOCKER_USER}/${DOCKER_REPO} | awk '{print $1":"$2}'); do
      docker push $p;
    done
  fi

notifications:
  slack:
    secure: JwJkvYYD4Q3iQi0pq6GNh2Blf9LLUVfOkfWIeMmomXYJgXyKsLvspnZdC+d8iQqQMAgDUkWS+K1EXVy92mcL+9YcGStlekuVF7hJCZlSJno3hLvtSrruA65JBwBojMKOZNZ7vtNCcFN/lVeFqUabrDezCzCSRYV+uTyVrXuqEnE=

# vim:set et ts=2 sw=2:
